### ISSUE TITLE
Moonraker unable to open gcode file

### ISSUE THREAD

**Issue by m3rguez0o** [jbatonnet/Rinkhals#5]
Another issue, when I send a gcode I doesn't send on the printer.
```

09:38:57 
$ G28
10:25:03 
$ SDCARD_PRINT_FILE FILENAME="Cube_PLA_0.28_1m2s.gcode"
10:28:10 
$ RESTART
10:28:11 
project state: Disconnect
10:32:14 
$ RESTART
10:32:15 
project state: Disconnect
10:32:29 
$ G28
10:44:08 
$ SDCARD_PRINT_FILE FILENAME="Cube_PLA_0.28_1m2s.gcode"
10:45:00 
$ SDCARD_PRINT_FILE FILENAME="Cube_PLA_0.28_1m2s.gcode"
10:45:56 
$ FIRMWARE_RESTART
10:45:58 
project state: Disconnect
10:46:21 
$ RESTART
10:46:22 
project state: Disconnect

```
I tested in Mainsail and Fluidd, it's the same.

[EDIT] here is the moonraker.log

```
-------------------- Log Start | Wed Dec 18 10:29:20 2024 --------------------
platform: Linux-5.10.160-armv7l-with-glibc2.39
data_path: /userdata/app/gk/printer_data
is_default_data_path: True
config_file: /userdata/app/gk/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: 8f1fd978f28c463f9a0bf655d9ee1c1d
unix_socket_path: /userdata/app/gk/printer_data/comms/moonraker.sock
software_version: ?
log_file: /userdata/app/gk/printer_data/logs/moonraker.log
python_version: 3.12.7 (main, Dec 11 2024, 23:16:27) [GCC 13.3.0]
launch_args: /usr/bin/python /usr/share/moonraker/moonraker/moonraker.py
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7126
klippy_uds_address = /tmp/unix_uds1
max_upload_size = 1024

[machine]
provider = none

[authorization]
cors_domains = 
	*://my.mainsail.xyz
	*://app.fluidd.xyz
	*://*.local
	*://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[database]

#################################################################
All Configuration Files:
/userdata/app/gk/printer_data/config/moonraker.conf
#################################################################
Loading Sqlite database provider. Sqlite Version: 3.46.1
Unsafe Shutdown Count: 3

System Info:

***python***
  version: (3, 12, 7, 'final', 0)
  version_string: 3.12.7 (main, Dec 11 2024, 23:16:27) [GCC 13.3.0]

***cpu_info***
  cpu_count: 1
  bits: 32bit
  processor: armv7l
  cpu_desc: ARMv7 Processor rev 5 (v7l)
  serial_number: db72ea92c1a33481
  hardware_desc: Generic DT based system
  model: 
  total_memory: 221056
  memory_units: kB

***sd_info***

***distribution***
  name: Buildroot 2024.08.3
  id: buildroot
  version: 2024.08.3
  version_parts: {'major': '2024', 'minor': '08', 'build_number': '3'}
  like: 
  codename: 
  release_info: {}
  kernel_version: 5.10.160

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
Module libcamera unavailble, import failed
2024-12-18 10:30:17,246 [application.py:log_request()] - 404 GET /server/files/klippy.log (192.168.1.24) [_TRUSTED_USER_] 40.46ms
2024-12-18 10:30:18,650 [application.py:log_request()] - 404 GET /server/files/klippy.log (192.168.1.24) [_TRUSTED_USER_] 19.12ms
2024-12-18 10:30:20,670 [application.py:log_request()] - 404 GET /server/files/klippy.log (192.168.1.24) [_TRUSTED_USER_] 17.53ms
2024-12-18 10:30:56,002 [klippy_apis.py:start_print()] - Requesting Job Start, filename = Cube_PLA_0.28_1m2s.gcode
2024-12-18 10:30:56,017 [job_queue.py:_pop_job()] - Error Loading print: Cube_PLA_0.28_1m2s.gcode
Traceback (most recent call last):
  File "/usr/share/moonraker/moonraker/components/job_queue.py", line 138, in _pop_job
    await kapis.start_print(
  File "/usr/share/moonraker/moonraker/components/klippy_apis.py", line 147, in start_print
    ret = await self.run_gcode(script)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/moonraker/moonraker/components/klippy_apis.py", line 123, in run_gcode
    result = await self._send_klippy_request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/moonraker/moonraker/components/klippy_apis.py", line 111, in _send_klippy_request
    result = await self.klippy.request(req)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/moonraker/moonraker/components/klippy_connection.py", line 584, in request
    return await self._request_standard(web_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/moonraker/moonraker/components/klippy_connection.py", line 678, in _request_standard
    return await base_request.wait(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/moonraker/moonraker/components/klippy_connection.py", line 789, in wait
    return await asyncio.wait_for(asyncio.shield(self._fut), to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
moonraker.utils.ServerError: Unable to open file: /useremain/app/gk/gcodes/Cube_PLA_0.28_1m2s.gcode
```

The file is well uploaded but not accessible by moonraker?
```
PowerShell 7.4.6
PS C:\Users\m3rgu> ssh root@192.168.1.45 -p2222
root@192.168.1.45's password:
root@Rockchip:~# cd /userdata/app/gk/printer_data/gcodes
root@Rockchip:/userdata/app/gk/printer_data/gcodes# ls
Cube_PLA_0.28_1m2s.gcode
root@Rockchip:/userdata/app/gk/printer_data/gcodes# ls -l
-rw-r--r--    1 root     root         88074 Cube_PLA_0.28_1m2s.gcode
root@Rockchip:/userdata/app/gk/printer_data/gcodes#

```

_Originally posted by @m3rguez0o in https://github.com/jbatonnet/Rinkhals/issues/4#issuecomment-2550870212_

**Comment by m3rguez0o** [comment]
Ok, I know, thank you!
I will install this release asap.
